// Kullanıcının Google Maps yorum ekranından sağladığı gerçek yorum dökümü.
// Google API kullanılmadığı için bu liste statik seed olarak PostgreSQL'e yazılır.
export const reviewsSummary = {
  average: 5,
  count: 149,
  source: "google",
};

const rows = [
  ["Erdem Kılınç", "bir ay önce", "Ankara İncek bölgesinde aracımızın aküsü aniden bittiği için acil akücü arayışına girdik. Telefonda hızlı dönüş yaptılar ve kısa sürede konumumuza gelip yerinde akü değişimi yaptılar. Özellikle yolda kalmış biri için hız ve güven çok önemli."],
  ["Ertunc Saracci", "4 ay önce", "Aracımın aküsü arızalandıktan sonra Akü Port firmasından yeni bir akü temin ettim ve aldığım hizmetten oldukça memnun kaldım. Kapıma kadar gelip taktılar. Ürün kaliteli ve performansı yüksek, aracım sorunsuz şekilde çalışmaya başladı."],
  ["serkan pekçetin", "8 ay önce", "Pazar günü olmasına rağmen Evren Bey hızlı bir şekilde marş basmayan akümün kontrollerini gerçekleştirdi ve sonuçları paylaştı. Makul bir fiyata 2025 üretimi Varta aküyü sorunsuz bir şekilde hızlıca taktı. İşini layığı ile yapan son derece ilgili bir işletme."],
  ["Taner Seyhan", "2 ay önce", "Evren bey konusunda uzman aracıma uygun akü önerdiği gibi verdiği bilgiler için de kendisine teşekkür ederim her akü bayisi böyle bilgili değil teşekkürler"],
  ["Ergin Yalı", "3 ay önce", "Evrim abi sağolsun akü sıkıntımızı ivedi ve çok kaliteli bir şekilde çözüme ulaştırdı. İşinin ehli, güvenilir ve güler yüzlü ustam."],
  ["G. S.", "9 ay önce", "Evren bey müşterilerine karşı son derece saygılı ve yardımcı. El çabukluğu, ustalığı ve neşeli mizacı ile tanımaktan çok mutlu olduğum bir usta. Kendisine bol kazançlı güzel günler diliyorum."],
  ["Yaren Öner", "9 ay önce", "Avm önünde farları açık unuttuk akü bitmiş ve pazar günü kapalı normalde şansımıza Hızır gibi yetiştiler Allah razın olsun ekmeğiniz kazancınız bol olsun"],
  ["tg", "6 ay önce", "Evren Abi, hızlı ve hakkaniyetli çözümler sunan bir insan. Kendisiyle tanıştığım için çok memnun kaldım."],
  ["Yolaçaner Consulting", "5 ay önce", "Evren Ustama teşekkür ederim. Mobil acil hizmetleri sayesinde telefonlaşmamızdan 15 dak sonra (Bilkent/Beytepe/İncek) yanımdaydı. Güleryüzlü ve güvenilir. 👍🏻🙏🏻"],
  ["Utk", "7 ay önce", "Evren Bey’in doğru yönlendirmeleri ve ilgisi sayesinde, doğru aküye uygun fiyata sahip olduk. Google Haritalar sayesinde tanıştığımız ve akümüzü değiştirdiğimiz bu işletmeyi herkese tavsiye ederim."],
  ["Gürkan Aslan", "9 ay önce", "Günlerden pazardı aile kahvaltısı diye araca inip araçtan uyarı almamız ile akü arayışına düştük."],
  ["Osman Turhan", "bir yıl önce", "Müthiş ilgi alaka, Evren abi çok yardımcı oldu. Herkese önerimdir ⭐️⭐️⭐️⭐️⭐️"],
  ["Recep Can", "bir yıl önce", "Akü fiyatları uygun. Seçenek çok 10 adet akü çeşidi var. Memnun kaldım hayırlı işler"],
  ["Sezgin Yıldız", "10 ay önce", "İncek taşpınarda aracımın aküsü bitti akü port'u aradım. evren abimiz kısa sürede yol yardım için geldi. aküyü değiştirdik aracım düzeldi. 7/24 Ankaranın heryerine hizmetimiz vardır dedi. Gerçekten güzel hizmet ve güler yüzlü kendileri. ilgi ve alakasından dolayı teşekkür ediyorum."],
  ["Mehmet Emin Keleş", "9 ay önce", "Kayseri Ankara istikametine İstanbul seyahat esnasında aracım akü problemi yaşadım firma ile iletişim kurdum kendileri en kısa sürede yol yardım ekibini yönlendirdi."],
  ["Halil Gorken", "8 ay önce", "Ümitköy'de akücü bulmaya çalışırken internetten aküportu buldum 15 dakikada geldi aküyü ölçtü ve değişimi yaptı. İşinin ehli birisi. Aldığım hizmetten memnun kaldım"],
  ["Egemen Okur", "bir yıl önce", "Akü değişimi için işini gerçekten kaliteli ve özenli yapan bir yer. Güler yüzlü ve samimi hizmetleriyle Evren bey işinde hem profesyonel hem de güvenilir bir esnaf. Herkese gönül rahatlığıyla tavsiye ederim."],
  ["Akif Özsarı", "bir yıl önce", "70 amper Start stop Bosch akü aldım. Fiyat ve montajdan memnun kaldım, hayırlı işler."],
  ["Mine Duru Demirel", "9 ay önce", "Yolda aküm bittiği an yardımıma yetiştiler. Hiç beklemedim çok yardımcı oldular çok memnun kaldım tekrardan teşekkür ediyorum."],
  ["yenereren01 yenereren01", "11 ay önce", "Ankara'nın bir ucundan diğerine hizmet var. Telefon iletişimi sonrası 15-20 dakikada uygun fiyatlı akü aracıma takıldı ve yoluma devam ettim. Teşekkürler Akü Port Evren Bey.🙏"],
  ["Eray", "7 ay önce", "Beytepe köyünde aracımın arıza yapması sebebi ile aramıştım. Sağolsun arkadaş 15 dakika içerisinde hemen gelip yardımcı oldu."],
  ["Umut Ates", "bir yıl önce", "Aracımın aküsü bitmek üzereyken bu işletmeye ulaştım. Beni hemen yerine davet etti ve sorunumu çözdü. Güleryüzü, hızlı hizmeti ve doğru fiyatı yüzünden Evren Bey’e teşekkür ederim."],
  ["herol heroglu", "bir yıl önce", "Hem işinin ehli hem de iyi bir insan. Sorun çıkınca da yüzüstü bırakmıyor. Şansı ve kazancı bol olsun. Bu zamanda böyle esnaf zor bulunur."],
  ["Umut Topaktas", "bir yıl önce", "Egea aracım için akü değişimi yaptım. Fiyatlar çevre işletmelere göre gayet makul. İşinin arkasında duran dürüst bir esnaf. Her türlü sorunda destek alabilirsiniz."],
  ["HÜSEYİN YURDAKUL", "11 ay önce", "Gölbaşından eryamana 30 dk da geldi evren Usta günümüz Türkiyesinde böyle profesyonel ve dürüst esnaf uzun zamandır görmemiştim. 5 dk da değiştirdi aküyü çok teşekkür ederim bol kazançlar ve başarılarınızın devamını diliyorum 👏👏👏"],
  ["Alkım Ege Akarsu", "bir yıl önce", "Ömrünün sonuna geldiğini düşündüğüm akümle gittiğimde ücretsiz olarak akümün sağladığı maksimum amper değeri test edildi ve tahminim doğrulandı. Hemen sonrasında 10 dakika içinde eski aküm çıkarıldı ve yenisi takıldı."],
  ["Hüseyin Selimoğlu", "bir yıl önce", "Aracım aküsü aniden bitti. Hemen internetten kısa bir araştırma yaptım. Aradım hemen geri dönüş sağladı. Akü fiyatları piyasaya göre çok iyi. 2 yıl garantili bir şekilde Varta EFB akü aldım. Garanti belgesini de verdi."],
  ["tolga Kaan", "10 ay önce", "Gece gündüz farketmez Evren kardeşimiz Hızır gibi her işimize koşar! Hiç bir aracımız sayesinde yolda kalmadı Akü Port’a sonsuz teşekkürler"],
  ["Onural ÇELİKHAN", "2 yıl önce", "Evren abinin misafirperverligi comertligi hizli ve temiz işçiliği HARIKA tesekkur ederim abi elime saglik KESINLIKLE TAVSIYE EDERIM..."],
  ["Furkan tuğlu", "bir ay önce", "Start stop akü aldm memnun kaldım👍🏻"],
  ["Kevser Aslandaş", "bir yıl önce", "Bu zamanda işinde dürüst bir esnafla karşılaşmak beni hem mutlu etti hem de çok memnun bıraktı. Piyasaya göre daha uygun fiyat, iki yıl garanti, hediye ettiği cam suyu ve güler yüzlü, ilgili davranışlarıyla Evren Bey’e çok teşekkür ederim. Kendisine bol kazançlar diliyorum."],
  ["Batuhan Üstündağ", "bir yıl önce", "Aniden aküm bitti, neyseki benzinlikteydim takviye yapıp yakındaki en yakın akücüye geldim. Yine Varta akü aldım, 10 dakikada aküm garantili olarak şaşmaz fiyatına değişti. Kibar, işine hakim iyi bir esnaf."],
  ["Mustafa Kemal SARIKAYA", "bir yıl önce", "Bilkent önünde araba çalışmadı Google dan buldum aradım sagolsunlar hemen gelip aküyü kontrol ettiler. Değişmesi gerektiğinden yenisini taktılar. İnternetten fiyatları karşılaştırdığımızda daha ucuza işimi çözdüklerini anladım. Sagolsunlar işleri rast gelsin"],
  ["Cn Ozyksl", "bir yıl önce", "Geçen akü aldım hem fiyatı çok uygundu hemde akü çok kaliteli müşteri ile nasıl ilgileneceğini bilen bi işletme çok teşekkür ederim"],
  ["Alka Group Gıda", "bir yıl önce", "Seçenek çok fazla ve çok hızlı yardımcı oldular. Teşekkür ederiz güzel hizmet ve uygun fiyat için :)"],
  ["Erman Tekdemir", "2 yıl önce", "İncek bölgesinde bulabileceğiniz en iyi akü montaj noktası. Dükkan sahibi Evren bey işinin ehli. Kış ortasında aracımı kaldığı yerden takviye ile kurtarıp yeni akü ile değişimini sağladı. Şiddetle tavsiye edilir!! :)"],
  ["Cengiz Çöçü", "bir yıl önce", "Arabamın biten aküsü için gitmiştim, hem güler yüzü hem de fiyat açısından çok mantıklı bir işletme. Evren beye teşekkürler..."],
  ["Yılmaz Poyraz Işık", "2 yıl önce", "Güleryüzlü esnaf işi bilen birisi fiyatlar makul ben memnun kaldım tavsiye ederim"],
  ["SAMİ ÖZTÜRK", "6 ay önce", "Start stop akü aldım memnun kaldım"],
  ["ea oz", "2 yıl önce", "Akü değişimine 200 tl dedi. Eski Aküyü de üstüne alırım dedi. Hemen 1 dakika ileride başka bir işletmeye, arabayı vurdurup gittim, aküyü değiştirdim."],
  ["Ilkhan özcan", "bir yıl önce", "hizmet efsane fiyatlarda gayet iyi esnaflık cidden ölmemiş hemen geldi taktı şarj çalıştırdı tanıdık tanımadık herkese tavsiye edecegim gerçek esnaf abimiz oldu"],
  ["Beytullah Atli", "7 ay önce", "Yerinde akü değişimi yaptı teşekkürler"],
  ["B. Y.", "8 ay önce", "Beytepe Eker Hastanesi önünde kaldım. En yakın akücü Evren abi geldi İnci Akü taktı sagolsun"],
  ["AY yıldız", "2 yıl önce", "Ankarada denk geldiğim en güzel yer Allah razı olsun herşey icin. Güvenle tavsiye ediyorum."],
  ["emrah uyaroğlu", "10 ay önce", "Evren bey çok ilgili ve işini çok iyi yapıyor. Bulvar lofta gelip akümü değişti. Teşekkürler"],
  ["Gökhan Kılınç", "2 yıl önce düzenlendi", "Akü ölçümü yaptırdım kaliteli hizmet, dürüst esnaf"],
  ["Burak Dinler", "2 yıl önce", "Evren abi çok teşekkürler, sıkıntımı 10 dakikada cözmekle kalmadi en uygun aküyü de taktı. Hıc dusunmeden burayi tercih edebilirsiniz."],
  ["Mehmet KAPAR", "2 yıl önce", "Evren abinin güler yüzü işçiliği fiyatı olsun her şeyi çok iyiydi ilgisi alakası olsun Allah razı olsun kendisinde. ŞİDDETLE TAVSİYE EDERİM!!"],
  ["Tayfun Kepez", "3 ay önce", "Güzel hizmet, güzel insan. Hayırlı işler dilerim."],
  ["Eglence Zamanı", "11 ay önce", "60 amper akü aldim ilği Alaka Çok Guzeldi Evren beyin muhabbeti Yeter"],
  ["Fazlı KÜÇÜK", "8 ay önce", "Işinde usta güler yüzlü herşey için teşekkürler 🤗"],
  ["rifki aydogan", "9 ay önce", "Akü takviyesi sonrası dükkanda akü değişimi yapıldı."],
  ["Ahmet Tosun", "2 yıl önce", "60 amper akü aldım. Konutkent e gelip aracıma akü montajı yapan Evren Beye teşekkür ediyorum"],
  ["Hacı Ali DURU", "bir yıl önce", "Evren usta Anında müdahale etti. Uygun fiyat kaliteli hizmet. Çok teşekkür ederim. Başarılar dilerim."],
  ["Tanıl Can Bayoğlu", "2 yıl önce", "Evren bey aramamın yarım saat sonrasında adresimdeydi. İyi iletişimi ve uygun fiyatıyla bana yardımcı oldu. Tereddüt etmeden hizmet alabilirsiniz. Teşekkürler Evren Bey"],
  ["Muharrem Şahiner", "2 yıl önce", "Beytepe de yolda kalmıştım aradığım da gelmeleri 8-10 dk bile sürmedi. Profesyonel oldukları çok belli. Kesinlikle tavsiye ederim."],
  ["AziZ Sezek", "2 yıl önce", "İşin hakkını veren gerçek bir profesyonel şehirdışından geliyorduk yol güzergahı üzerinde iken bize Hızır gibi yetişti eakişehirden selamlar ustama"],
  ["Tayfun Özgüder", "10 ay önce", "Güvenilir ve kaliteli hizmet aldım. Teşekkür ederim."],
  ["İbrahim Y", "bir yıl önce", "Telefon ettim. 30 dk. içinde gelip akümü değiştirdiler. Güleryüzlü ve işini özenle yapan bir esnaf."],
  ["Ensar Başiş", "9 ay önce", "İşletme sahibi kadar güzel ve temiz kesinlikle tavsiye ederim"],
  ["Batuhan Öztürk", "2 yıl önce", "Güler yüzlü işletmeci, üstün hizmet"],
  ["natre natre", "2 yıl önce", "Evren abi gerçekten on numara insan başka ilden buraya geldim misafir perver yardımcı oldu aracımızla ilgilendi burdan teşekkür ediyorum kendisine"],
  ["Hasan Hüseyin Yayılkan", "2 yıl önce", "Beytepede aku montajı yaptılar. Sanayıye gitmeye gerek yok, fıyatlar uygun. Memnun kaldım, teşekkürler hayırlı işler."],
  ["Veli Yücel", "6 ay önce", "Güler yüzlü bir işletme kaliteli ve işini iyi bilen bir işletme"],
  ["CELEBİ ONLÜEL", "10 ay önce", "Ferce Tulumtaş a gelip akü taktı sagolsun."],
  ["Ferhan Işılak", "2 yıl önce", "Akü değişimi yaptık Evren bey çok ilgiliydi memnun kaldık tavsiye ederim"],
  ["Emin Rufaioğlu", "bir yıl önce", "Çok memnun kaldım Evren abi işinde çok iyi ve işçiliği çok memnun kaldım Allah razı olsun"],
  ["Ahmet Metehan Yıldız", "bir yıl önce", "Usta çok ilgilendi kendisi düzgün bir esnaf, çok memnun kaldım dükkanda seçenek çok."],
  ["“Necmettin” Nusret Ekmekçi", "bir yıl önce", "Çok çabuk ve kolayca halledildi, işinin ehli ve dürüst esnaf olmaları da beni çok memnun etti. Evren beye çok teşekkürler"],
  ["İrfan Sabri Demir", "bir yıl önce", "Evren Bey sağolsun evimize kadar geldi ve hemen çözüm sağladı. Çok memnun kaldım."],
  ["Ali Şanlı", "bir yıl önce", "Evren bey çok ilgili yardımcı oldu taksit imkanı var."],
  ["KIRAÇ", "2 yıl önce", "Sıcak kanlı esnaf yolda kaldık yardımcı oldu."],
  ["Mustafa Buyukarslan", "bir yıl önce", "Gayet memnun kaldık incek tokiye tereddütsüz geldiler yardimci oldu arkadaşlar teşekkür ederiz"],
  ["Edgar Allan Poe", "bir yıl önce", "Anında dönüş sağlayıp gerçekten ilgilenen dürüst bir işletme, herkese tavsiye ederim"],
  ["Sancar Bayar", "bir yıl önce", "Çok düzgün ve profesyonel bir işletme, Evren beye teşekkür ediyorum"],
  ["AHMET Özel", "8 ay önce", "Çok ilgili ve her zaman malının arkasında duran bir satıcı."],
  ["Hüseyin Bahçeli", "2 yıl önce", "Hızlı bir şekilde geldi akümüzü yerinde değiştirdik fiyatlar piyasaya göre uygun tavsiye ederim"],
  ["kadri yücesoy", "2 yıl önce", "İncek bölgesi için iyi bir dükkan. Hizmeti kaliteli. Mekan sahibi işini iyi bilen saygılı bir arkadaş. Dostlarıma, arkadaşlarıma tavsiye ederim."],
  ["Harun ÖZDEMİR", "10 ay önce", "Agm akü aldım hızlı çözdüler teşekkürler"],
  ["Abdullah Doğan", "2 yıl önce", "90 ah. akü aldım. Evren Beye teşekkürler hayırlı işler."],
  ["İsmail kalır", "8 ay önce", "Dört dörtlük işletme kesinlikle tavsiye ederim."],
  ["Fahrettin Akbayrak", "bir yıl önce", "Güvenilir sözünün arkasında duran insan gibi esnaf aldığı helal hoş olsun"],
  ["Dilay Reyhanli", "bir yıl önce", "Beyefendi çok güler yüzlü, ilgili ve bilgiliydi. Her şey için teşekkür ederim"],
  ["Ahmet Göksoy", "10 ay önce", "Çok memnun kaldık, tavsiye ederiz."],
  ["New Holland", "bir yıl önce", "Gayet işine sadık güvenilir çok candan birisi"],
  ["ESAT Tasdemir", "2 yıl önce", "Fiyatları çok uygun ve ayrıca ilgi ve alakasından dolayı Evren Beye teşekkür ederim"],
  ["EA", "bir yıl önce", "Hem profesyonel, hem hızlı, hem ilgili, 10 numara bir ustamız"],
  ["kerem kuş", "bir yıl önce", "Hızlı ve profesyönel bir değişim. İşini hakkıyla yapan bir yer"],
  ["ebru sahiner", "2 yıl önce", "Aracıma 74 ah Varta akü aldım, tavsiye ederim."],
  ["YMK KUŞ VLOG", "2 yıl önce", "İnci aku aldım fıyat cok uyguna geldi. Hizmet kalite on numara"],
  ["Bunyamin Durum", "bir yıl önce", "Zengin ürün çeşidi ile hizmet vermektedir. Kalite tesadüf değildir"],
  ["Serdar Senel", "bir yıl önce", "Gayet güzel esnaflığı bilen samimi işinizi anında çözebileceğiz bir yer"],
  ["S ANALYSIS", "2 yıl önce", "Yolda kalmıştım bana yardımcı oldu ilgi ve yardımı için teşekkür ederim çok düzgün bir esnaf"],
  ["Emrah Satilmis", "bir yıl önce", "Gerçek bir esnaf hizmeti anlayışı tercubesi herşey on numara"],
  ["Görkem Efe Çelik", "bir yıl önce", "İşçilik kalite olarak her şey çok iyi. Güvenilir."],
  ["deniz yüksel", "2 yıl önce", "İşinin ehli çok iyi sahibi. Hızlı bir şekilde işimi halleti."],
  ["UğurCan DEMİR", "6 ay önce", "Güler yüz ve kalitenin adresi"],
  ["M. Ahmet Çetinkaya", "bir yıl önce", "Çok yardımcı oldu her konuda kesinlikle tavsiye ederim"],
  ["Birol Sırakaya", "bir yıl önce", "Efb akü buradan alınır 👍"],
  ["Ugur Erat", "2 yıl önce", "Hemen yardımcı oldular piyasaya göre fiyatları gayet makul"],
  ["Caner GÜL", "10 ay önce", "ACİL DESTEK TEK ÇÖZÜM ÇOK HIZLI ÇOK TEŞEKKÜRLER"],
  ["Mehmet Ali HIŞMANOĞLU", "7 ay önce", "Çok kaliteli müşteri memnuniyeti çok iyi"],
  ["Mustafa Karataş", "bir yıl önce", "Evren abiye ilgisi ve yardımı için çok teşekkür ederim"],
  ["Furkan Dursun", "bir yıl önce", "İşini güler yüzle yapan esnaf"],
  ["Caner Yılmaz", "bir yıl önce", "İlgilerinden dolayı teşekkür ederiz."],
  ["Kadir Patlak", "bir yıl önce", "Güler yüzlü kaliteli hizmet"],
  ["İsa Dal", "2 yıl önce", "Çok memnun kaldım. Teşekkür ederim"],
  ["Tugay Tunç", "2 yıl önce", "Hızlı ve güvenilir hizmet"],
  ["Böcek İlaçlama", "11 ay önce", "İlgisinden dolayı çok teşekkürler"],
  ["Ozan Kelkit", "2 yıl önce", "Hızlı ve guleryuzlu hizmet"],
  ["serkan daşkın", "2 yıl önce", "Çok memnun kaldım tavsiye ederim."],
  ["Barış Gokmen", "2 yıl önce", "Teşekkür"],
  ["Berat yıldırım", "bir yıl önce", "Çok memnun kaldım"],
  ["Emre Sahinbay", "2 yıl önce", "Çok ilgili davrandılar."],
  ["Bahri Berk Yüceloğlu", "7 ay önce", ""],
  ["Mustafa Ulusoy", "bir hafta önce", ""],
  ["İbrahim DURMAZ", "bir ay önce", ""],
  ["Onurcan Sönmez", "bir ay önce", ""],
  ["Sarp Akyol", "bir ay önce", ""],
  ["Nazif Çiftçi", "bir ay önce", ""],
  ["Selver Altıparmak", "2 ay önce", ""],
  ["naznaz naz", "2 ay önce", ""],
  ["Halil", "2 ay önce", ""],
  ["Eşref", "3 ay önce", ""],
  ["vahit özmen", "5 ay önce", ""],
  ["Sinan Karakaya", "5 ay önce", ""],
  ["servet yucel", "7 ay önce", ""],
  ["sina Nasiri", "7 ay önce", ""],
  ["Enes Gökalp", "8 ay önce", ""],
  ["TheDoor", "8 ay önce", ""],
  ["Emrullah Keçeli", "8 ay önce", ""],
  ["Hasan Fehmi Kara", "9 ay önce", ""],
  ["Tarık ÖZEN", "10 ay önce", ""],
  ["Musa Arslan", "11 ay önce", ""],
  ["Severse Döner", "bir yıl önce", ""],
  ["Ali Aşır", "bir yıl önce", ""],
  ["ali karabal", "bir yıl önce", ""],
  ["Mete Oral", "bir yıl önce", ""],
  ["Fuat Kapan İş Makinası Off Road", "bir yıl önce", ""],
  ["Emir Türkşanlı", "bir yıl önce", ""],
  ["Atila Çİftçi", "bir yıl önce", ""],
  ["Sarp Göktuğ GÜMÜŞ", "bir yıl önce", ""],
  ["Yiğitcan Karagöz", "bir yıl önce", ""],
  ["Oğuzhan Doğan", "bir yıl önce", ""],
  ["mehmet yaman", "bir yıl önce", ""],
  ["Mustafa Örgülü", "bir yıl önce", ""],
  ["Alper", "bir yıl önce", ""],
  ["Cagri Metin", "bir yıl önce", ""],
  ["hakan yücel", "2 yıl önce", ""],
];

export const reviews = rows.map(([author, time, text], index) => ({
  id: index + 1,
  author,
  rating: 5,
  text,
  time,
  avatar: "",
  source: "google",
  approved: true,
}));
